

{
    "name": "Property Management System",
    "version": "13.0.1.0.0",
    "author": "Dawit Yilma",
    "category": "Extra Tools",
    "website": "https://github.com/DawitYilma",
    "depends": ["mail", "sale", "payment", "portal", "utm", "website"],
    "license": "AGPL-3",
    "summary": "property Management Software",
    "demo": [],
    "data": [
            'security/security.xml',
            'security/ir.model.access.csv',
            'views/menus.xml',
            'views/property_details.xml',
            'views/tenant_details.xml',
            'views/tenant_details_line.xml',
            'views/property_type.xml',
            'views/image_details.xml',
            'views/tenant_details_line.xml',
            'views/maintenance.xml',
            'views/maintenance_type.xml',
            'views/reporting.xml',
            'views/assets.xml',
            'views/order_refresh.xml',
            'views/maintenance_website.xml',
            'views/terms_conditions.xml',
            'data/tenant_details_sequence.xml',
            'data/tenant_details_line_cron.xml',
            'data/property_details_sequence.xml',
            'data/property_maintenance_sequence.xml',
            'reports/report.xml',
            'reports/tenantdetails.xml',
            'reports/tenantdetailsline.xml',
            ],
    "external_dependencies": {"python": ["dateutil"]},
    "images": [],
    "installable": True,
    "application": True,
}
