from . import property_details
from . import tenant_details
from . import property_type
from . import property_sales
from . import account_move
from . import sale_make_invoice_advance
from . import property_maintenance
from . import terms_conditions
from . import order_refresh
